version: 2.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.2.2
    working_directory: ~/GameProgressTracker
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: bundle install

  deploy:
    docker:
      - image: cimg/ruby:3.2.2
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICaQB4GKgeM8O+HAiR9kYkbVQQmHo1nWrcOa8rkd5F0n moyosore921@gmail.com"
      - run:
          name: Deploy to EC2
          command: |
            echo "Deploying to EC2..."
            docker login -u "moyosore09" -p "thisisthis09"
            docker pull cloudapp:latest || true
            docker build -t cloudapp .
            docker tag cloudapp:latest cloudapp:$(date +'%Y%m%d%H%M%S')
            docker push cloudapp:latest
            docker push cloudapp:$(date +'%Y%m%d%H%M%S')
            ssh -i cloud_aws.pem ubuntu@ip-172-31-35-24 "docker-compose -f GameProgressTracker\docker-compose.yml pull && docker-compose -f GameProgressTracker\docker-compose.yml up -d"