version: 2

jobs:
  build:
    docker:
      - image: cimg/ruby:3.2.2
      - image: circleci/postgres:13.3
    working_directory: ~/GameProgressTracker
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            bundle install
      - run:
          name: Database setup
          command: |
            bundle exec rake db:create db:migrate
      - run:
          name: Start Rails server
          command: |
            bundle exec rails server -b 0.0.0.0

  deploy:
    docker:
      - image: cimg/ruby:3.2.2
    steps:
      - run:
          name: Deploy to EC2
          command: |
            echo "Deploying to EC2..."
            scp -i cloud_aws.pem -r ./ ubuntu@ip-172-31-35-24:http://16.171.153.138:3000/games
            ssh -i cloud_aws.pem ubuntu@ip-172-31-35-24: "cd http://16.171.153.138:3000/games && bundle install && rake db:migrate && sudo service cloudApp restart"