workflows:
  version: 2
  builds:
    jobs:
      - build:
        branches:
          only:
            -main
      - deploy:
        filters:
          branches:
            only:
              - main
        requires:
          - build:
          


orbs:
  ruby: circleci/ruby@1.4.0

jobs:
  build:
    working_directory: ~/GameProgressTracker
    docker:
      - image: cimg/ruby:3.2.2
    steps:
      -checkout
      - setup_remote_docker
      - run:
          name: hello 
          command: echo hello
  deploy:
    docker:
      - image: cimg/ruby:3.2.2
    steps:
      - run:
          name: world
          commandL: echo world